export default [] = [
    {
        id: 1,
        title: "Simple Form",
        img: "https://raw.githubusercontent.com/Hnafy/Portfolio/main/public/image/Screenshots/simple-form.jpeg",
        page: "https://hanafy-form.netlify.app/",
        category: ["all", "html","tw","react"],
        body: "Lorem ipsum dolor sit amet consectetur elit adipisicing . Ex tempore dolor in, accusantium laudantium accusamus.",
    },
    {
        id: 2,
        title: "Social Media App",
        img: "https://raw.githubusercontent.com/Hnafy/Portfolio/main/public/image/Screenshots/tarmeez.jpeg",
        page: "https://tarmeez.netlify.app/",
        category: ["all", "html","css","js"],
        body: "Lorem ipsum dolor sit amet consectetur elit adipisicing . Ex tempore dolor in, accusantium laudantium accusamus.",
    },
    {
        id: 3,
        title: "Slider",
        img: "https://raw.githubusercontent.com/Hnafy/Portfolio/main/public/image/Screenshots/slider.jpeg",
        page: "https://hanafy-slider.netlify.app/",
        category: ["all", "html","css","react"],
        body: "Lorem ipsum dolor sit amet consectetur elit adipisicing . Ex tempore dolor in, accusantium laudantium accusamus.",
    },
    {
        id: 4,
        title: "Todo App",
        img: "https://raw.githubusercontent.com/Hnafy/Portfolio/main/public/image/Screenshots/todo.jpeg",
        page: "https://hanafy-todo.netlify.app/",
        category: ["all", "html","css","react"],
        body: "Lorem ipsum dolor sit amet consectetur elit adipisicing . Ex tempore dolor in, accusantium laudantium accusamus.",
    },
    {
        id: 5,
        title: "Guess World",
        img: "https://raw.githubusercontent.com/Hnafy/Portfolio/main/public/image/Screenshots/guess-world.jpeg",
        page: "https://hanafy-guess-world.netlify.app/",
        category: ["all", "html","css","react"],
        body: "Lorem ipsum dolor sit amet consectetur elit adipisicing . Ex tempore dolor in, accusantium laudantium accusamus.",
    },
    {
        id: 6,
        title: "Quiz App",
        img: "https://raw.githubusercontent.com/Hnafy/Portfolio/main/public/image/Screenshots/quiz-app.jpeg",
        page: "https://hanafy-quiz-app.netlify.app/",
        category: ["all", "html","tw","react"],
        body: "Lorem ipsum dolor sit amet consectetur elit adipisicing . Ex tempore dolor in, accusantium laudantium accusamus.",
    },
    {
        id: 7,
        title: "E-Commerce",
        img: "https://raw.githubusercontent.com/Hnafy/Portfolio/main/public/image/Screenshots/e-commerce.jpeg",
        page: "https://hanafy-e-commerce.netlify.app/",
        category: ["all", "html","tw","react"],
        body: "Lorem ipsum dolor sit amet consectetur elit adipisicing . Ex tempore dolor in, accusantium laudantium accusamus.",
    },
    {
        id: 8,
        title: "Prayer times",
        img: "https://github.com/Hnafy/Tarmeez_Prayer_Times/blob/main/public/Prayer%20Times.jpeg?raw=true",
        page: "https://main--hanafy-prayer-times.netlify.app/",
        category: ["all", "html","css","react"],
        body: "Lorem ipsum dolor sit amet consectetur elit adipisicing . Ex tempore dolor in, accusantium laudantium accusamus.",
    },
];
